### ISSUE TITLE
Better name

### ISSUE THREAD

**Issue by asmeurer** [gforsyth/doctr#1]

**Comment by asmeurer** [comment]
Any thoughts on this?  I think we have about enough to do a first release.

**Comment by gforsyth** [comment]
Well, there's @Carreau's kind offer of 'documentation'

Other random things:
Doctr
Travails
Indoctrination
Tradoc (rhymes with haddock)
Paginator (probably taken)
Traverse
Indoxicate

OK, I'm done for now

On Jul 21, 2016 4:25 PM, "Aaron Meurer" <notifications@github.com> wrote:

Any thoughts on this? I think we have about enough to do a first release.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/gforsyth/travis_docs_builder/issues/1#issuecomment-234372835>,
or mute the thread

**Comment by Carreau** [comment]
`buildthedocs`

**Comment by gforsyth** [comment]
I'm ok with that if we aren't stepping on anyone's toes.

**Comment by Carreau** [comment]
> I'm ok with that if we aren't stepping on anyone's toes.

With `buildthedocs` ? I'll reach out.

**Comment by asmeurer** [comment]
I like doctr. `buildthedocs` is taken on PyPI.

**Comment by asmeurer** [comment]
paginator and traverse are taken on PyPI. The rest aren't.

**Comment by Carreau** [comment]
> buildthedocs is taken on PyPI.

Dang.

**Comment by asmeurer** [comment]
travails, tradoc, and indoxicate are not taken as GitHub orgs (the rest are). 

I also like travails because it indicates how annoying this is when you try to do this manually. I don't like how easy it is to misspell, though.

**Comment by gforsyth** [comment]
doctr then? 5 letter libraries have a history of success

**Comment by gforsyth** [comment]
Phone email is slow. I'm good with whatever

**Comment by gforsyth** [comment]
What if we register all the common misspellings of travails on pypi?

**Comment by asmeurer** [comment]
How important is having the GitHub name? I do like doctr best.

**Comment by asmeurer** [comment]
Also there's apparently a band called Doctr https://www.youtube.com/watch?v=1IouOi6LeHs&list=PL6UJ1iWYZviomWoTkHu7O5U0T7cS7Y1jB

**Comment by gforsyth** [comment]
I don't think the organization name is too important, we could have it be
pydoctr or doctrpy or some such, name the repo doctr and grab the package
name on pypi
